# Generated by Django 3.2.6 on 2021-08-18 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
