# Generated by Django 3.2.6 on 2021-08-18 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210819_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 3 uppercase character', regex='^[A-Z]{3}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='spending',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency'),
        ),
    ]
