# Generated by Django 3.2.6 on 2021-08-19 00:25
from django.db import migrations

def seed_currencies(apps, schema_editor):
    Currency = apps.get_model("api", "Currency")
    Currency.objects.create(name="Hungarian Forint", code="HUF")
    Currency.objects.create(name="Euro", code="EUR")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210819_0112'),
    ]

    operations = [
        migrations.RunPython(seed_currencies),
    ]
